### ISSUE TITLE
NPE: Cannot invoke "String.length()" because "suffix" is null

### ISSUE THREAD

**Issue by onewhl** [JetBrains-Research/RefactorInsight#105]
Project: https://github.com/JetBrains/Arend
Commit: 7a22759be067534970e82d854f605310abad6f34
Stacktrace:
```java
Cannot invoke "String.length()" because "suffix" is null
java.lang.NullPointerException: Cannot invoke "String.length()" because "suffix" is null
	at java.base/java.lang.String.endsWith(String.java:2315)
	at org.jetbrains.research.refactorinsight.ui.DiffHintLineMarkerProvider.fromSameFile(DiffHintLineMarkerProvider.java:124)
	at org.jetbrains.research.refactorinsight.ui.DiffHintLineMarkerProvider.lambda$getRefactoringInfos$3(DiffHintLineMarkerProvider.java:116)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at org.jetbrains.research.refactorinsight.ui.DiffHintLineMarkerProvider.getRefactoringInfos(DiffHintLineMarkerProvider.java:116)
	at org.jetbrains.research.refactorinsight.ui.DiffHintLineMarkerProvider.collectSlowLineMarkers(DiffHintLineMarkerProvider.java:65)

```

**Comment by anchouls** [comment]
I don't have this error on this commit. Also, refactorings aren't recognized on this commit, so this function shouldn't be called.
