### ISSUE TITLE
Plugin's column doesn't appear in the Log tab anymore

### ISSUE THREAD

**Issue by onewhl** [JetBrains-Research/RefactorInsight#125]
In the previous releases, there was a possibility to add a plugin column to the Log tab that appeared if we detected some refactorings in the commit.

<img width="581" alt="Screen Shot 2023-03-14 at 11 59 18 AM" src="https://user-images.githubusercontent.com/10652414/224980814-de2350e9-81d1-477f-a76d-8fa72ec7cc91.png">

**Comment by onewhl** [comment]
Stacktrace from a user:
`com.intellij.diagnostic.PluginException: Cannot create extension (class=org.jetbrains.research.refactorinsight.ui.windows.RefactoringColumn) [Plugin: org.jetbrains.research.refactorinsight]
	at com.intellij.serviceContainer.ComponentManagerImpl.createError(ComponentManagerImpl.kt:1096)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:70)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.kt:31)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.notifyListeners(ExtensionPointImpl.java:747)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.addExtensionPointListener(ExtensionPointImpl.java:779)
	at com.intellij.vcs.log.ui.table.column.VcsLogColumnManager.registerCustomColumns(VcsLogColumnManager.kt:68)
	at com.intellij.vcs.log.ui.table.column.VcsLogColumnManager.<init>(VcsLogColumnManager.kt:54)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:993)
	at com.intellij.serviceContainer.ComponentManagerImpl.createLightService(ComponentManagerImpl.kt:970)
	at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService(ComponentManagerImpl.kt:774)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:726)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:670)
	at com.intellij.vcs.log.ui.table.column.VcsLogColumnManager$Companion.getInstance(VcsLogColumnManager.kt:153)
	at com.intellij.vcs.log.ui.table.column.VcsLogColumnManager.getInstance(VcsLogColumnManager.kt)
	at com.intellij.vcs.log.ui.table.GraphTableModel.getColumnCount(GraphTableModel.java:53)
	at java.desktop/javax.swing.JTable.createDefaultColumnsFromModel(JTable.java:1355)
	at java.desktop/javax.swing.JTable.tableChanged(JTable.java:4449)
	at java.desktop/javax.swing.JTable.setModel(JTable.java:3751)
	at com.intellij.ui.table.JBTable.setModel(JBTable.java:386)
	at java.desktop/javax.swing.JTable.<init>(JTable.java:705)
	at com.intellij.ui.table.JBTable.<init>(JBTable.java:92)
	at com.intellij.vcs.log.ui.table.TableWithProgress.<init>(TableWithProgress.java:15)
	at com.intellij.vcs.log.ui.table.VcsLogGraphTable.<init>(VcsLogGraphTable.java:131)
	at com.intellij.vcs.log.ui.frame.MainFrame$MyVcsLogGraphTable.<init>(MainFrame.java:428)
	at com.intellij.vcs.log.ui.frame.MainFrame.<init>(MainFrame.java:108)
	at git4idea.ui.branch.dashboard.BranchesVcsLogUi.createMainFrame(BranchesDashboardUi.kt:363)
	at com.intellij.vcs.log.ui.VcsLogUiImpl.<init>(VcsLogUiImpl.java:74)
	at git4idea.ui.branch.dashboard.BranchesVcsLogUi.<init>(BranchesDashboardUi.kt:349)
	at git4idea.ui.branch.dashboard.BranchesVcsLogUiFactory.createVcsLogUiImpl(BranchesDashboardUi.kt:343)
	at com.intellij.vcs.log.impl.VcsLogManager$BaseVcsLogUiFactory.createLogUi(VcsLogManager.java:330)
	at com.intellij.vcs.log.impl.VcsLogManager.createLogUi(VcsLogManager.java:164)
	at com.intellij.vcs.log.impl.VcsLogContentProvider.addMainUi(VcsLogContentProvider.java:100)
	at com.intellij.vcs.log.impl.VcsLogContentProvider.<init>(VcsLogContentProvider.java:69)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1007)
	at com.intellij.openapi.vcs.changes.ui.ChangesViewContentEP.newClassInstance(ChangesViewContentEP.java:187)
	at com.intellij.openapi.vcs.changes.ui.ChangesViewContentEP.getInstance(ChangesViewContentEP.java:139)
	at com.intellij.openapi.vcs.changes.ui.VcsToolWindowFactoryKt$createExtensionContent$1$1.invoke(VcsToolWindowFactory.kt:159)
	at com.intellij.openapi.vcs.changes.ui.ChangesViewContentManager.initLazyContent(ChangesViewContentManager.kt:186)
	at com.intellij.openapi.vcs.changes.ui.ChangesViewContentManager$ContentProvidersListener.selectionChanged(ChangesViewContentManager.kt:202)
	at jdk.internal.reflect.GeneratedMethodAccessor154.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:120)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:85)
	at jdk.proxy2/jdk.proxy2.$Proxy190.selectionChanged(Unknown Source)
	at com.intellij.ui.content.impl.ContentManagerImpl.fireSelectionChanged(ContentManagerImpl.java:621)
	at com.intellij.ui.content.impl.ContentManagerImpl.addSelectedContent(ContentManagerImpl.java:432)
	at com.intellij.ui.content.impl.ContentManagerImpl$2.run(ContentManagerImpl.java:520)
	at com.intellij.ui.content.impl.ContentManagerImpl.lambda$setSelectedContent$4(ContentManagerImpl.java:533)
	at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:177)
	at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
	at com.intellij.openapi.util.ActionCallback.doWhenProcessed(ActionCallback.java:129)
	at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContent(ContentManagerImpl.java:533)
	at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContentCB(ContentManagerImpl.java:485)
	at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContent(ContentManagerImpl.java:470)
	at com.intellij.openapi.wm.impl.content.ContentTabLabel.selectContent(ContentTabLabel.java:154)
	at com.intellij.openapi.wm.impl.content.ContentTabLabel.handleMouseClick(ContentTabLabel.java:48)
	at com.intellij.openapi.wm.impl.content.ContentLabel$1.execute(ContentLabel.java:41)
	at com.intellij.util.ui.BaseButtonBehavior$MyMouseListener.execute(BaseButtonBehavior.java:184)
	at com.intellij.util.ui.BaseButtonBehavior$MyMouseListener.mouseReleased(BaseButtonBehavior.java:166)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6656)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
	at java.desktop/java.awt.Component.processEvent(Component.java:6421)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2804)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:790)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:666)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:614)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:569)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:994)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:994)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.research.refactorinsight.ui.windows.RefactoringColumn PluginClassLoader(plugin=PluginDescriptor(name=RefactorInsight, id=org.jetbrains.research.refactorinsight, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2023.1\plugins\plugin, version=2023.1-1.0, package=null, isBundled=false), packagePrefix=null, instanceId=440, state=active)
	at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:1629)
	at com.intellij.serviceContainer.ComponentManagerImplKt.access$doLoadClass(ComponentManagerImpl.kt:1)
	at com.intellij.serviceContainer.ComponentManagerImpl.loadClass(ComponentManagerImpl.kt:984)
	at com.intellij.openapi.extensions.impl.InterfaceExtensionImplementationClassResolver.resolveImplementationClass(InterfaceExtensionImplementationClassResolver.kt:24)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:49)
	... 119 more`
