### ISSUE TITLE
 assert: ComponentStoreImpl.doAddComponent

### ISSUE THREAD

**Issue by onewhl** [JetBrains-Research/refactorinsight#34]
```
Product: IDEA 201.8538.31   Plugin: RefactorInsight 2020.1-1.1   OS: Mac OS X   Java: JetBrains s.r.o. 11.0.7   Reporter: Anonymous IDEA User   Date: 2020-07-13 14:58  

    

java.lang.Throwable: Conflicting component name 'MiningRefactoringsState': class services.MiningService and class org.jetbrains.research.refactorinsight.services.MiningService (componentManager=Project (name=RefactoringMiner, containerState=ACTIVE, componentStore=/Users/ioana/Desktop/RefactoringMiner) )
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
    at com.intellij.configurationStore.ComponentStoreImpl.doAddComponent(ComponentStoreImpl.kt:352)
    at com.intellij.configurationStore.ComponentStoreImpl.initPersistenceStateComponent(ComponentStoreImpl.kt:137)
    at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:103)
    at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:50)
    at com.intellij.serviceContainer.ComponentManagerImpl.initializeComponent$intellij_platform_serviceContainer(ComponentManagerImpl.kt:358)
    at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:58)
    at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:115)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:69)
    at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:411)
    at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:394)
    at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:24)
    at org.jetbrains.research.refactorinsight.services.MiningService.getInstance(MiningService.java:54)
    at org.jetbrains.research.refactorinsight.processors.CommitListener.repositoryChanged(CommitListener.java:15)
    at jdk.internal.reflect.GeneratedMethodAccessor441.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:541)
    at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:139)
    at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:465)
    at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:426)
    at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:415)
    at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:395)
    at com.intellij.util.messages.impl.MessageBusImpl.lambda$createTopicHandler$3(MessageBusImpl.java:237)
    at com.sun.proxy.$Proxy123.dirtyUnder(Unknown Source)
    at git4idea.annotate.GitRepositoryForAnnotationsListener$1.repositoryChanged(GitRepositoryForAnnotationsListener.java:46)
    at jdk.internal.reflect.GeneratedMethodAccessor441.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:541)
    at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:143)
    at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:465)
    at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:426)
    at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:415)
    at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:397)
    at com.intellij.util.messages.impl.MessageBusImpl.lambda$createTopicHandler$3(MessageBusImpl.java:237)
    at com.sun.proxy.$Proxy122.repositoryChanged(Unknown Source)
    at git4idea.repo.GitRepositoryManager.lambda$notifyListenersAsync$3(GitRepositoryManager.java:113)
    at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
    at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
    at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
    at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:210)
    at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:190)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by onewhl** [comment]
It seems it's a toy report send from IDE to test that the reports are collected indeed. No need to fix
