### ISSUE TITLE
Handle new refactoring types introduced in last RefactoringMiner release

### ISSUE THREAD

**Issue by onewhl** [JetBrains-Research/RefactorInsight#94]
Plugin crashes when tries to process unsupported refactoring types that were introduced in the last RefactoringMiner release.
For example, `CHANGE_CLASS_ACCESS_MODIFIER` refactoring. 
`java.lang.IllegalArgumentException: No enum constant org.jetbrains.research.refactorinsight.adapters.RefactoringType.CHANGE_CLASS_ACCESS_MODIFIER
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at org.jetbrains.research.refactorinsight.adapters.RefactoringType.valueOf(RefactoringType.java:51)
	at org.jetbrains.research.refactorinsight.data.InfoFactory.create(InfoFactory.java:19)
	at org.jetbrains.research.refactorinsight.data.RefactoringEntry.lambda$convertJavaRefactorings$1(RefactoringEntry.java:96)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.jetbrains.research.refactorinsight.data.RefactoringEntry.convertJavaRefactorings(RefactoringEntry.java:96)
	at org.jetbrains.research.refactorinsight.processors.CommitMiner$1.handle(CommitMiner.java:104)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:158)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAtCommit(GitHistoryRefactoringMinerImpl.java:569)
`
We need to check what refactoring types were introduced and support them in our plugin.

**Comment by onewhl** [comment]
Resolved in #100
